name: Build APK Android
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Hoặc phiên bản mới nhất
      
      - name: Cai dat thu vien
        run: flutter pub get
        
      - name: Xay dung APK
        run: flutter build apk --release
        
      - name: Upload APK len Github
        uses: actions/upload-artifact@v4
        with:
          name: file-cai-dat-apk
          path: build/app/outputs/flutter-apk/app-release.apk
